---
title: "Peer review publications"
---

- Serafim, M. B.; Almendra, R.; Barrozo, L. V.; Santana, P. (2026). Socioeconomic deprivation and mortality in megacities during the first two decades of the 21st century: A scoping review of area-based studies". Social Sciences & Humanities Open. [DOI: 10.1016/j.ssaho.2025.102406](https://doi.org/10.1016/j.ssaho.2025.102406)
- Serafim, M. B.; Santana, A. P.; Corsi, A. C.; Barrozo, L. V. (2025). A Socioenvironmental Deprivation Index for slum health research in the municipality of São Paulo, Brazil. Cities & Health, 1-15. [DOI: 10.1080/23748834.2025.2461858](https://doi.org/10.1080/23748834.2025.2461858)
- Barrozo, L. V.; Serafim, M. B.; Gomes, L.A.C.; Uhrigshardt, G. G.; Martins, N. F. A.; Oliveira, T. F.; Resende, J. F.; Amaro Jr., E. (2024). Targeting the “poorest of the poor”: A multi-scale approach. Socio-Economic Planning Sciences, 93, 101903. [DOI: 10.1016/j.seps.2024.101903](https://doi.org/10.1016/j.seps.2024.101903)
- Barrozo, L. V.; Serafim, M. B.; Moraes, Sara Lopes de; Mansur, Giselle. (2020). "MONITORAMENTO ESPAÇO-TEMPORAL DAS ÁREAS DE ALTO RISCO DE COVID-19 NOS MUNICÍPIOS DO BRASIL. Hygeia - Revista Brasileira de Geografia Médica e da Saúde, 417-425. [DOI: 10.14393/hygeia0054547](https://doi.org/10.14393/hygeia0054547)
- Serafim, M. B.; Siegle, E.; Corsi, A. C.; Bonetti, J. (2019). Coastal vulnerability to wave impacts using a multi-criteria index: Santa Catarina (Brazil). Journal of Environmental Management 230, 21-32. [DOI: 10.1016/j.jenvman.2018.09.052](https://doi.org/10.1016/j.jenvman.2018.09.052)
- Bonetti, J.; Rudorff, F. de M.; Campos, A. V.; Serafim, M. B. (2018). Geoindicator-based assessment of Santa Catarina (Brazil) sandy beaches susceptibility to erosion". Ocean & Coastal Management 156, 198-208. [DOI:10.1016/j.ocecoaman.2017.08.009](https://doi.org/10.1016/j.ocecoaman.2017.08.009)
- Serafim, M. B.; Bonetti, J. (2017). Vulnerabilidade das praias do Estado de Santa Catarina a eventos de erosão e inundação costeira: proposta metodológica baseada em um índice multicritério. Quaternary and Environmental Geosciences, 8(2). [DOI:10.5380/abequa.v8i2.47281](https://doi.org/10.5380/abequa.v8i2.47281)